language: python
sudo: false
python: 3.7
services:
- docker
branches:
  only: master
install:
- pip install --upgrade pip setuptools
- pip install --upgrade tox
env:
  global:
  - PYTHONUNBUFFERED=x
  - PYPI_USERNAME=wellcomedigitalplatform
  - secure: fhiogZWjNrz3o/PRbcB/0Qtpk5bN2eiLwNWFlVbJRcMJJ6Z7aiBMzJyrVBE/bS7O87MxWRScvGnGcEydZe7OMeCckc+gkyuwrfVj5bGgs8wYj6w5GZheuVskWXNcOPHYuPms3NKU9CXpWo06Qbvv/RL9ydI3N+QfSm8Ph0s1S0nOTTPsc1IqVZ5eP8C/XaNLPXN4IExkIx4XluizmcYjnYEbExAvbZp4ZsqrPK5INk9TKFJ2pvfeQjGFjtq54XsDtfOTouexnNJmDWWxKgeaEq5IbuZuMby5mUjevx0Yar0JqMx9eWYfYoxBH34piQ3Tf9CWQmqlRfixtUfyKxm0PvkLM0NFSpJCU8I9N0cF6okMRNep2JUNngoARis68EAWVJ9dfQ7hT2I2FO5XYuFhBDv0dldZ+1YpVOAEdTLfRICpIg504Lx921KbCjG/I6Pcn5lDCYqPwsf0FUXfs+ZERUfv9XRL340LbmiVKt3rdLrXZtBpUkFAOwjL0lefyWZIdumPQqiMLqa6XobxAeLdC1cpGjZ8i5cHqJft9rpXzDJKn/d6M29qOhfR2NhyYBU+V5lPuvRXlkX3B4UyFeBLvufCE5QNPj+e4zICTYdR01lPtV8SyJs2m6mbm5EKSQXr68uYStQSXzkPbM+qxKX1VrEwnPloZf143L1VsSUxCUI=
  - secure: MHSrnXju/0ORj3ukTrp4HxVzpWL5Fq8bRMMXULBtXmuFgyR+cIUYOJa1bg69xUZzW0TLp3cbSS6IGev+qESEupRqlN19k6/1+NEluFVwkIer0I24bwYtXoryOuztZgEMAe0FhKn/h0Uy4V3DBzUKLXHX1QohxFBqo29cZVbh7yl8ND6Dk/kHztevWIRV/ilfoohSej+mGBRTOSYMzSzK9OV/+TaqeRxXOQYayjPQtYvMAZUpBb1Dfk6DA8zXibbY2n2pYiJv58/qCM+7o+ZtKTGrUr1cq9pfvQbDTWIVeWNV3BKoBd+Y6OW9hHaqau/f+MKmAFK+BroMlHfHEFVk7Ha0ZMO+TBCeZ+XoHo6YmPFv460U+oYnX6G5jvvWJV6n6mesQtvIOilmM8O+b0c42I+vjWCK+93gLiMSlnGLqjUxgn/oMlTxGo2nWKYSC89gp4vMeVXP9PCJMLjgt+07EAC2uPLDJ3wxhhpnH6tvpEKgLkH2WDPcIPFokHQYG6p+LnhBjoGXtXk6pchkYiaubMZn0H6r6N1QJuyXfyALthll74iggzs/oCIiek7GEuBlSjp5EBX1Ht1vc72w4AzKGYvgI3OqAF6nlcRKpS0i/Vicy2m6h/+nO+C07MOzakcT1sWuOt4ngGb2BVUv87N8zuKh2w55NN9SL4hlpgtAlCY=
jobs:
  include:
  - stage: test
    env: TOXENV=lint
    name: lint
  - env: TOXENV=check_release_file
    name: check_release_file
  - env: TOXENV=py37
    name: build_python_package
  - stage: deploy
    env: TOXENV=deploy
    name: deploy_to_pypi
  - env: TOXENV=docker_build
    name: docker_build
stages:
- test
- name: deploy
  if: type = push
script:
- tox
