language: python
sudo: false
python: 3.7
branches:
  only: master
install:
- pip install --upgrade pip setuptools
- pip install --upgrade tox
env:
  global:
  # This forces Python to print everything to stdout/stderr immediately.
  # Otherwise, we've seen issues where all the output from our Travis scripts
  # gets buffered, and only gets printed at the end of the test...
  #
  # ... out of order from the rest of the rest of the output!
  #
  # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
  #
  - PYTHONUNBUFFERED=x
  - PYPI_USERNAME=wellcomedigitalplatform
  # This contains the following variables:
  #  - PYPI_PASSWORD
  - secure: "fhiogZWjNrz3o/PRbcB/0Qtpk5bN2eiLwNWFlVbJRcMJJ6Z7aiBMzJyrVBE/bS7O87MxWRScvGnGcEydZe7OMeCckc+gkyuwrfVj5bGgs8wYj6w5GZheuVskWXNcOPHYuPms3NKU9CXpWo06Qbvv/RL9ydI3N+QfSm8Ph0s1S0nOTTPsc1IqVZ5eP8C/XaNLPXN4IExkIx4XluizmcYjnYEbExAvbZp4ZsqrPK5INk9TKFJ2pvfeQjGFjtq54XsDtfOTouexnNJmDWWxKgeaEq5IbuZuMby5mUjevx0Yar0JqMx9eWYfYoxBH34piQ3Tf9CWQmqlRfixtUfyKxm0PvkLM0NFSpJCU8I9N0cF6okMRNep2JUNngoARis68EAWVJ9dfQ7hT2I2FO5XYuFhBDv0dldZ+1YpVOAEdTLfRICpIg504Lx921KbCjG/I6Pcn5lDCYqPwsf0FUXfs+ZERUfv9XRL340LbmiVKt3rdLrXZtBpUkFAOwjL0lefyWZIdumPQqiMLqa6XobxAeLdC1cpGjZ8i5cHqJft9rpXzDJKn/d6M29qOhfR2NhyYBU+V5lPuvRXlkX3B4UyFeBLvufCE5QNPj+e4zICTYdR01lPtV8SyJs2m6mbm5EKSQXr68uYStQSXzkPbM+qxKX1VrEwnPloZf143L1VsSUxCUI="
jobs:
  include:
  - env: TOXENV=lint
  - env: TOXENV=check_release_file
  - env: TOXENV=py37
  - env: TOXENV=deploy
    stage: deploy
stages:
- test
- name: deploy
  if: type = push
script:
- tox
