version: "3.3"
services:
  tox:
    build:
      context: .
      dockerfile: tox.Dockerfile
    volumes:
      - .:/workdir
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${SSH_AUTH_SOCK}:/ssh-agent.sock
      # Expose the host Docker socket and config inside the container.  Both of these
      # are required for Docker to run correctly inside the container.
      #
      #   - The socket allows Docker-in-Docker to start new containers
      #   - The config allows Docker-in-Docker to share credentials with Docker on
      #     the host, e.g. to push images to ECR
      #
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG}:/root/.docker
    environment:
      - CI=true
      - TOXENV
      - SSH_AUTH_SOCK=/ssh-agent.sock
