version: "3.3"
services:
  tox:
    build:
      context: .
      dockerfile: tox.Dockerfile
    volumes:
      - .:/workdir
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ${SSH_AUTH_SOCK}:/ssh-agent.sock
    environment:
      - TOXENV
      - SSH_AUTH_SOCK=/ssh-agent.sock
