version: "3.3"
services:
  tox:
    build:
      context: .
      dockerfile: tox.Dockerfile
    volumes:
      - .:/workdir
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${SSH_AUTH_SOCK}:/ssh-agent.sock
      # Expose the host Docker socket inside the container. This
      # is required for Docker to run correctly inside the container.
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.aws:/root/.aws
    environment:
      - CI=true
      - TOXENV
      - SSH_AUTH_SOCK=/ssh-agent.sock
