steps:
  - label: "lint"
    plugins:
      - docker-compose#v3.5.0:
          run: tox
          env:
            - TOXENV=lint
  - label: "check_release_file"
    plugins:
      - docker-compose#v3.5.0:
          run: tox
          env:
            - TOXENV=check_release_file
  - label: "test"
    plugins:
      - docker-compose#v3.5.0:
          run: tox
          env:
            - TOXENV=py37
  - wait
  - label: "pypi publish"
    if: build.branch == "master"
    plugins:
      - seek-oss/aws-sm#v2.1.0:
          env:
            PYPI_PASSWORD: builds/pypi_password
      - docker-compose#v3.5.0:
          run: tox
          env:
            - TOXENV=deploy
            - PYPI_USERNAME=wellcomedigitalplatform
            - PYPI_PASSWORD
  - wait
  - label: "docker hub publish"
    if: build.branch == "master"
    plugins:
      - seek-oss/aws-sm#v2.1.0:
          env:
            DOCKER_HUB_PASSWORD: builds/docker_hub_password
      - docker-compose#v3.5.0:
          run: tox
          env:
            - TOXENV=docker_build
            - DOCKER_HUB_PASSWORD
